/// The kind of playlist.
public struct PlaylistKind: RawRepresentable, Codable, Hashable, Sendable {
    public var rawValue: String

    /// A regular/manual playlist.
    public static let regular = Self(rawValue: "Regular")
    /// A dynamic playlist generated from a set of rules.
    public static let smart = Self(rawValue: "Smart")
    /// A playlist iTunes creates of songs that go well together.
    public static let genius = Self(rawValue: "Genius")
    /// A playlist folder.
    public static let folder = Self(rawValue: "Folder")
    /// An ongoing radio station-like playlist in a particular genre generated by iTunes.
    public static let geniusMix = Self(rawValue: "Genius Mix")

    public init(rawValue: String) {
        self.rawValue = rawValue
    }
}
